openapi: 3.0.0
info:
  title: Rimac Appointments API
  version: "1.0.0"
  description: Documentación de la API de citas médicas de Rimac
paths:
  /appointment:
    post:
      summary: Crea una cita
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                insuredId:
                  type: string
                scheduleId:
                  type: number
                countryISO:
                  type: string
      responses:
        '200':
          description: Cita creada exitosamente
  /appointment/{insuredId}:
    get:
      summary: Obtiene las citas por insuredId
      parameters:
        - name: insuredId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de citas
